#PBS -q regular
#PBS -l nodes=1
#PBS -l walltime=02:00:00
#PBS -N run100
#PBS -e run100.$PBS_JOBID.err
#PBS -o run100.$PBS_JOBID.out
#PBS -V

cd $PBS_O_WORKDIR
export OMP_NUM_THREADS=16
#export KMP_AFFINITY=balanced
#get_micfile
get_hostfile
#mpirun.mic -n 4 -hostfile micfile.$PBS_JOBID -ppn 1 ./myexe.mic

export I_MPI_PIN_DOMAIN=32,compact
export KMP_AFFINITY=scatter,verbose
exe=/chos/global/u1/v/vadlaman/homme-r4317-vec-refac/perfTestOB/test_execs/perfTest/perfTest
input=input.nl

export OMP_NUM_THREADS=16

#for k in $(seq 1 1 10)
#  do
#    mpirun -n 1 $exe < $input
#    mv HommeTime HommeTime.${k}
#    echo $k
#    sleep 5
#  done
mpirun -n 1 $exe < $input
